finger_information:
  - tip_link: 'A3_Link'
    contact_pt:
      position: [0.045, 0.01222, -0.006] 
      orientation: [-1.57, 0.0, 0.0]
    open_dir: [0.0, -1.0, -1.0]
  - tip_link: 'B3_Link'
    contact_pt:
      position: [0.045, 0.01222, -0.0012]
      orientation: [-1.57, 0.0, 0.0]
    open_dir: [-1.0, -1.0]
  - tip_link: 'C3_Link'
    contact_pt:
      position: [0.045, 0.0122, 0.0]
      orientation: [-1.57, 0.0, -0.0015]
    open_dir: [0.0, -1.0, -1.0]
open_hand_config: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
symmetries:
  - ['A3_Link', 'C3_Link']
code_position_weight: 5.0